[user]
username = "fedevitale99@gmail.com"
password = "Fagocero99"

[notifications]
webhook = "https://discord.com/api/webhooks/802113582430421002/LOsFzYQFC8ug0GeKF_JqkeHAz4tBWL5darsYUhHYRf9IpU_Dqwaia5zsSvTbXZJ2Pj7N"
